onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate -format Literal /test/reset
add wave -noupdate -format Logic /test/c_clk
add wave -noupdate -format Literal -radix unsigned /test/req1_cmd_in
add wave -noupdate -format Literal -radix unsigned /test/req1_data_in
add wave -noupdate -format Literal -radix unsigned /test/req2_cmd_in
add wave -noupdate -format Literal -radix unsigned /test/req2_data_in
add wave -noupdate -format Literal -radix unsigned /test/req3_cmd_in
add wave -noupdate -format Literal -radix unsigned /test/req3_data_in
add wave -noupdate -format Literal -radix unsigned /test/req4_cmd_in
add wave -noupdate -format Literal -radix unsigned /test/req4_data_in
add wave -noupdate -format Literal /test/out_resp1
add wave -noupdate -format Literal -radix unsigned /test/out_data1
add wave -noupdate -format Literal /test/out_resp2
add wave -noupdate -format Literal -radix unsigned /test/out_data2
add wave -noupdate -format Literal /test/out_resp3
add wave -noupdate -format Literal -radix unsigned /test/out_data3
add wave -noupdate -format Literal /test/out_resp4
add wave -noupdate -format Literal -radix unsigned /test/out_data4
add wave -noupdate -group into_design
add wave -noupdate -group into_design -format Logic /test/scan_out
add wave -noupdate -group into_design -format Logic /test/a_clk
add wave -noupdate -group into_design -format Logic /test/b_clk
add wave -noupdate -group into_design -format Literal /test/error_found
add wave -noupdate -group into_design -format Logic /test/scan_in
add wave -noupdate -group into_design -format Literal /test/add/add_pin
add wave -noupdate -group into_design -format Literal /test/add/oper1
add wave -noupdate -group into_design -format Literal /test/add/oper2
add wave -noupdate -group into_design -format Literal /test/direct_test/out_data1
add wave -noupdate -group into_design -format Literal /test/direct_test/out_data2
add wave -noupdate -group into_design -format Literal /test/direct_test/out_data3
add wave -noupdate -group into_design -format Literal /test/direct_test/out_data4
add wave -noupdate -group into_design -format Literal /test/direct_test/out_resp1
add wave -noupdate -group into_design -format Literal /test/direct_test/out_resp2
add wave -noupdate -group into_design -format Literal /test/direct_test/out_resp3
add wave -noupdate -group into_design -format Literal /test/direct_test/out_resp4
add wave -noupdate -group into_design -format Logic /test/direct_test/scan_out
add wave -noupdate -group into_design -format Logic /test/direct_test/a_clk
add wave -noupdate -group into_design -format Logic /test/direct_test/b_clk
add wave -noupdate -group into_design -format Logic /test/direct_test/c_clk
add wave -noupdate -group into_design -format Literal /test/direct_test/error_found
add wave -noupdate -group into_design -format Literal /test/direct_test/req1_cmd_in
add wave -noupdate -group into_design -format Literal /test/direct_test/req2_cmd_in
add wave -noupdate -group into_design -format Literal /test/direct_test/req3_cmd_in
add wave -noupdate -group into_design -format Literal /test/direct_test/req4_cmd_in
add wave -noupdate -group into_design -format Literal /test/direct_test/req1_data_in
add wave -noupdate -group into_design -format Literal /test/direct_test/req2_data_in
add wave -noupdate -group into_design -format Literal /test/direct_test/req3_data_in
add wave -noupdate -group into_design -format Literal /test/direct_test/req4_data_in
add wave -noupdate -group into_design -format Literal /test/direct_test/reset
add wave -noupdate -group into_design -format Logic /test/direct_test/scan_in
add wave -noupdate -group into_design -format Literal /test/direct_test/add_sum
add wave -noupdate -group into_design -format Literal /test/direct_test/fxu_areg_q
add wave -noupdate -group into_design -format Literal /test/direct_test/fxu_breg_q
add wave -noupdate -group into_design -format Literal /test/direct_test/shift_out
add wave -noupdate -group into_design -format Literal /test/direct_test/shift_places
add wave -noupdate -group into_design -format Literal /test/direct_test/shift_val
add wave -noupdate -group into_design -format Literal /test/direct_test/hold1_data1
add wave -noupdate -group into_design -format Literal /test/direct_test/hold1_data2
add wave -noupdate -group into_design -format Literal /test/direct_test/hold2_data1
add wave -noupdate -group into_design -format Literal /test/direct_test/hold2_data2
add wave -noupdate -group into_design -format Literal /test/direct_test/hold3_data1
add wave -noupdate -group into_design -format Literal /test/direct_test/hold3_data2
add wave -noupdate -group into_design -format Literal /test/direct_test/hold4_data1
add wave -noupdate -group into_design -format Literal /test/direct_test/hold4_data2
add wave -noupdate -group into_design -format Literal /test/direct_test/mux1_req_data1
add wave -noupdate -group into_design -format Literal /test/direct_test/mux1_req_data2
add wave -noupdate -group into_design -format Literal /test/direct_test/mux2_req_data1
add wave -noupdate -group into_design -format Literal /test/direct_test/mux2_req_data2
add wave -noupdate -group into_design -format Literal /test/direct_test/mux3_req_data1
add wave -noupdate -group into_design -format Literal /test/direct_test/mux3_req_data2
add wave -noupdate -group into_design -format Literal /test/direct_test/mux4_req_data1
add wave -noupdate -group into_design -format Literal /test/direct_test/mux4_req_data2
add wave -noupdate -group into_design -format Literal /test/direct_test/hold1_prio_req
add wave -noupdate -group into_design -format Literal /test/direct_test/hold2_prio_req
add wave -noupdate -group into_design -format Literal /test/direct_test/hold3_prio_req
add wave -noupdate -group into_design -format Literal /test/direct_test/hold4_prio_req
add wave -noupdate -group into_design -format Literal /test/direct_test/prio_alu1_in_cmd
add wave -noupdate -group into_design -format Literal /test/direct_test/prio_alu2_in_cmd
add wave -noupdate -group into_design -format Literal /test/direct_test/mux1_req_resp1
add wave -noupdate -group into_design -format Literal /test/direct_test/mux1_req_resp2
add wave -noupdate -group into_design -format Literal /test/direct_test/mux2_req_resp1
add wave -noupdate -group into_design -format Literal /test/direct_test/mux2_req_resp2
add wave -noupdate -group into_design -format Literal /test/direct_test/mux3_req_resp1
add wave -noupdate -group into_design -format Literal /test/direct_test/mux3_req_resp2
add wave -noupdate -group into_design -format Literal /test/direct_test/mux4_req_resp1
add wave -noupdate -group into_design -format Literal /test/direct_test/mux4_req_resp2
add wave -noupdate -group into_design -format Literal /test/direct_test/prio_alu1_in_req_id
add wave -noupdate -group into_design -format Literal /test/direct_test/prio_alu1_out_req_id
add wave -noupdate -group into_design -format Literal /test/direct_test/prio_alu2_in_req_id
add wave -noupdate -group into_design -format Literal /test/direct_test/prio_alu2_out_req_id
add wave -noupdate -group into_design -format Logic /test/direct_test/prio_alu1_out_vld
add wave -noupdate -group into_design -format Logic /test/direct_test/prio_alu2_out_vld
add wave -noupdate -group into_design -format Logic /test/direct_test/scan_ring1
add wave -noupdate -group into_design -format Logic /test/direct_test/scan_ring2
add wave -noupdate -group into_design -format Logic /test/direct_test/scan_ring3
add wave -noupdate -group into_design -format Logic /test/direct_test/scan_ring4
add wave -noupdate -group into_design -format Logic /test/direct_test/scan_ring5
add wave -noupdate -group into_design -format Logic /test/direct_test/scan_ring6
add wave -noupdate -group into_design -format Logic /test/direct_test/add_ovfl
add wave -noupdate -group into_design -format Logic /test/direct_test/shift_ovfl
add wave -noupdate -group into_design -format Logic /test/direct_test/adder/bin_ovfl
add wave -noupdate -group into_design -format Literal /test/direct_test/adder/bin_sum
add wave -noupdate -group into_design -format Literal /test/direct_test/adder/alu_cmd
add wave -noupdate -group into_design -format Literal /test/direct_test/adder/fxu_areg_q
add wave -noupdate -group into_design -format Literal /test/direct_test/adder/fxu_breg_q
add wave -noupdate -group into_design -format Logic /test/direct_test/adder/local_error_found
add wave -noupdate -group into_design -format Literal /test/direct_test/adder/p
add wave -noupdate -group into_design -format Literal /test/direct_test/adder/p_n
add wave -noupdate -group into_design -format Literal /test/direct_test/adder/g
add wave -noupdate -group into_design -format Literal /test/direct_test/adder/h_n
add wave -noupdate -group into_design -format Literal /test/direct_test/adder/d
add wave -noupdate -group into_design -format Literal /test/direct_test/adder/a
add wave -noupdate -group into_design -format Literal /test/direct_test/adder/a_n
add wave -noupdate -group into_design -format Literal /test/direct_test/adder/b
add wave -noupdate -group into_design -format Literal /test/direct_test/adder/b_n
add wave -noupdate -group into_design -format Literal /test/direct_test/adder/fxu_areg_n_q
add wave -noupdate -group into_design -format Literal /test/direct_test/adder/fxu_breg_n_q
add wave -noupdate -group into_design -format Literal /test/direct_test/adder/c
add wave -noupdate -group into_design -format Literal /test/direct_test/adder/c_n
add wave -noupdate -group into_design -format Literal /test/direct_test/adder/G2
add wave -noupdate -group into_design -format Literal /test/direct_test/adder/P2
add wave -noupdate -group into_design -format Literal /test/direct_test/adder/Gn
add wave -noupdate -group into_design -format Literal /test/direct_test/adder/Pn
add wave -noupdate -group into_design -format Literal /test/direct_test/adder/Gb
add wave -noupdate -group into_design -format Literal /test/direct_test/adder/Pb
add wave -noupdate -group into_design -format Literal /test/direct_test/adder/d8
add wave -noupdate -group into_design -format Literal /test/direct_test/adder/G2b
add wave -noupdate -group into_design -format Literal /test/direct_test/adder/P2b
add wave -noupdate -group into_design -format Logic /test/direct_test/adder/ds
add wave -noupdate -group into_design -format Logic /test/direct_test/adder/bin_a_z_q
add wave -noupdate -group into_design -format Logic /test/direct_test/adder/bin_add_45_q
add wave -noupdate -group into_design -format Literal /test/direct_test/adder/bin_by_f_e_q
add wave -noupdate -group into_design -format Logic /test/direct_test/adder/bin_cin_q
add wave -noupdate -group into_design -format Logic /test/direct_test/adder/bin_ex_sign_q
add wave -noupdate -group into_design -format Logic /test/direct_test/adder/bin_ex_sign_op_q
add wave -noupdate -group into_design -format Logic /test/direct_test/adder/bin_sub_45_q
add wave -noupdate -group into_design -format Logic /test/direct_test/adder/bin_sub_q
add wave -noupdate -group into_design -format Logic /test/direct_test/adder/bin_c_0
add wave -noupdate -group into_design -format Logic /test/direct_test/adder/bin_c_32
add wave -noupdate -group into_design -format Logic /test/direct_test/adder/bin_sum_0_63_z
add wave -noupdate -group into_design -format Logic /test/direct_test/adder/bin_sum_32_63_z
add wave -noupdate -group into_design -format Logic /test/direct_test/adder/bin_sum_33_63_z
add wave -noupdate -group into_design -format Literal /test/direct_test/adder/bruce_bin_sum
add wave -noupdate -group into_design -format Literal /test/direct_test/adder/A
add wave -noupdate -group into_design -format Literal /test/direct_test/adder/B
add wave -noupdate -group into_design -format Literal /test/direct_test/adder/C
add wave -noupdate -group into_design -format Literal /test/direct_test/adder/D
add wave -noupdate -group into_design -format Literal /test/direct_test/adder/E
add wave -noupdate -group into_design -format Literal /test/direct_test/adder/F
add wave -noupdate -group into_design -format Literal /test/direct_test/adder/G
add wave -noupdate -group into_design -format Literal /test/direct_test/adder/H
add wave -noupdate -group into_design -format Literal /test/direct_test/adder/I
add wave -noupdate -group into_design -format Literal /test/direct_test/adder/J
add wave -noupdate -group into_design -format Literal /test/direct_test/adder/K
add wave -noupdate -group into_design -format Literal /test/direct_test/adder/L
add wave -noupdate -group into_design -format Literal /test/direct_test/adder/M
add wave -noupdate -group into_design -format Literal /test/direct_test/adder/N
add wave -noupdate -group into_design -format Literal /test/direct_test/adder/O
add wave -noupdate -group into_design -format Literal /test/direct_test/adder/P
add wave -noupdate -group into_design -format Literal /test/direct_test/adder/Q
add wave -noupdate -group into_design -format Literal /test/direct_test/adder/R
add wave -noupdate -group into_design -format Literal /test/direct_test/adder/S
add wave -noupdate -group into_design -format Logic /test/direct_test/holdreg1/a_clk
add wave -noupdate -group into_design -format Logic /test/direct_test/holdreg1/b_clk
add wave -noupdate -group into_design -format Logic /test/direct_test/holdreg1/c_clk
add wave -noupdate -group into_design -format Logic /test/direct_test/holdreg1/scan_in
add wave -noupdate -group into_design -format Literal /test/direct_test/holdreg1/req_cmd_in
add wave -noupdate -group into_design -format Literal /test/direct_test/holdreg1/reset
add wave -noupdate -group into_design -format Literal /test/direct_test/holdreg1/req_data_in
add wave -noupdate -group into_design -format Logic /test/direct_test/holdreg1/scan_out
add wave -noupdate -group into_design -format Literal /test/direct_test/holdreg1/hold_prio_req
add wave -noupdate -group into_design -format Literal /test/direct_test/holdreg1/hold_data1
add wave -noupdate -group into_design -format Literal /test/direct_test/holdreg1/hold_data2
add wave -noupdate -group into_design -format Literal /test/direct_test/holdreg1/cmd_hold
add wave -noupdate -group into_design -format Literal /test/direct_test/holdreg1/hold_prio_reg
add wave -noupdate -group into_design -format Literal /test/direct_test/holdreg1/cmd_hold_q
add wave -noupdate -group into_design -format Literal /test/direct_test/holdreg1/hold_data1_q
add wave -noupdate -group into_design -format Literal /test/direct_test/holdreg1/hold_data2_q
add wave -noupdate -group into_design -format Logic /test/direct_test/holdreg2/a_clk
add wave -noupdate -group into_design -format Logic /test/direct_test/holdreg2/b_clk
add wave -noupdate -group into_design -format Logic /test/direct_test/holdreg2/c_clk
add wave -noupdate -group into_design -format Logic /test/direct_test/holdreg2/scan_in
add wave -noupdate -group into_design -format Literal /test/direct_test/holdreg2/req_cmd_in
add wave -noupdate -group into_design -format Literal /test/direct_test/holdreg2/reset
add wave -noupdate -group into_design -format Literal /test/direct_test/holdreg2/req_data_in
add wave -noupdate -group into_design -format Logic /test/direct_test/holdreg2/scan_out
add wave -noupdate -group into_design -format Literal /test/direct_test/holdreg2/hold_prio_req
add wave -noupdate -group into_design -format Literal /test/direct_test/holdreg2/hold_data1
add wave -noupdate -group into_design -format Literal /test/direct_test/holdreg2/hold_data2
add wave -noupdate -group into_design -format Literal /test/direct_test/holdreg2/cmd_hold
add wave -noupdate -group into_design -format Literal /test/direct_test/holdreg2/hold_prio_reg
add wave -noupdate -group into_design -format Literal /test/direct_test/holdreg2/cmd_hold_q
add wave -noupdate -group into_design -format Literal /test/direct_test/holdreg2/hold_data1_q
add wave -noupdate -group into_design -format Literal /test/direct_test/holdreg2/hold_data2_q
add wave -noupdate -group into_design -format Logic /test/direct_test/holdreg3/a_clk
add wave -noupdate -group into_design -format Logic /test/direct_test/holdreg3/b_clk
add wave -noupdate -group into_design -format Logic /test/direct_test/holdreg3/c_clk
add wave -noupdate -group into_design -format Logic /test/direct_test/holdreg3/scan_in
add wave -noupdate -group into_design -format Literal /test/direct_test/holdreg3/req_cmd_in
add wave -noupdate -group into_design -format Literal /test/direct_test/holdreg3/reset
add wave -noupdate -group into_design -format Literal /test/direct_test/holdreg3/req_data_in
add wave -noupdate -group into_design -format Logic /test/direct_test/holdreg3/scan_out
add wave -noupdate -group into_design -format Literal /test/direct_test/holdreg3/hold_prio_req
add wave -noupdate -group into_design -format Literal /test/direct_test/holdreg3/hold_data1
add wave -noupdate -group into_design -format Literal /test/direct_test/holdreg3/hold_data2
add wave -noupdate -group into_design -format Literal /test/direct_test/holdreg3/cmd_hold
add wave -noupdate -group into_design -format Literal /test/direct_test/holdreg3/hold_prio_reg
add wave -noupdate -group into_design -format Literal /test/direct_test/holdreg3/cmd_hold_q
add wave -noupdate -group into_design -format Literal /test/direct_test/holdreg3/hold_data1_q
add wave -noupdate -group into_design -format Literal /test/direct_test/holdreg3/hold_data2_q
add wave -noupdate -group into_design -format Logic /test/direct_test/holdreg4/a_clk
add wave -noupdate -group into_design -format Logic /test/direct_test/holdreg4/b_clk
add wave -noupdate -group into_design -format Logic /test/direct_test/holdreg4/c_clk
add wave -noupdate -group into_design -format Logic /test/direct_test/holdreg4/scan_in
add wave -noupdate -group into_design -format Literal /test/direct_test/holdreg4/req_cmd_in
add wave -noupdate -group into_design -format Literal /test/direct_test/holdreg4/reset
add wave -noupdate -group into_design -format Literal /test/direct_test/holdreg4/req_data_in
add wave -noupdate -group into_design -format Logic /test/direct_test/holdreg4/scan_out
add wave -noupdate -group into_design -format Literal /test/direct_test/holdreg4/hold_prio_req
add wave -noupdate -group into_design -format Literal /test/direct_test/holdreg4/hold_data1
add wave -noupdate -group into_design -format Literal /test/direct_test/holdreg4/hold_data2
add wave -noupdate -group into_design -format Literal /test/direct_test/holdreg4/cmd_hold
add wave -noupdate -group into_design -format Literal /test/direct_test/holdreg4/hold_prio_reg
add wave -noupdate -group into_design -format Literal /test/direct_test/holdreg4/cmd_hold_q
add wave -noupdate -group into_design -format Literal /test/direct_test/holdreg4/hold_data1_q
add wave -noupdate -group into_design -format Literal /test/direct_test/holdreg4/hold_data2_q
add wave -noupdate -group into_design -format Literal /test/direct_test/in_stage1/alu_data1
add wave -noupdate -group into_design -format Literal /test/direct_test/in_stage1/alu_data2
add wave -noupdate -group into_design -format Literal /test/direct_test/in_stage1/hold1_data1
add wave -noupdate -group into_design -format Literal /test/direct_test/in_stage1/hold1_data2
add wave -noupdate -group into_design -format Literal /test/direct_test/in_stage1/hold2_data1
add wave -noupdate -group into_design -format Literal /test/direct_test/in_stage1/hold2_data2
add wave -noupdate -group into_design -format Literal /test/direct_test/in_stage1/hold3_data1
add wave -noupdate -group into_design -format Literal /test/direct_test/in_stage1/hold3_data2
add wave -noupdate -group into_design -format Literal /test/direct_test/in_stage1/hold4_data1
add wave -noupdate -group into_design -format Literal /test/direct_test/in_stage1/hold4_data2
add wave -noupdate -group into_design -format Literal /test/direct_test/in_stage1/prio_alu_in_cmd
add wave -noupdate -group into_design -format Literal /test/direct_test/in_stage1/prio_alu_in_req_id
add wave -noupdate -group into_design -format Literal /test/direct_test/in_stage2/alu_data1
add wave -noupdate -group into_design -format Literal /test/direct_test/in_stage2/alu_data2
add wave -noupdate -group into_design -format Literal /test/direct_test/in_stage2/hold1_data1
add wave -noupdate -group into_design -format Literal /test/direct_test/in_stage2/hold1_data2
add wave -noupdate -group into_design -format Literal /test/direct_test/in_stage2/hold2_data1
add wave -noupdate -group into_design -format Literal /test/direct_test/in_stage2/hold2_data2
add wave -noupdate -group into_design -format Literal /test/direct_test/in_stage2/hold3_data1
add wave -noupdate -group into_design -format Literal /test/direct_test/in_stage2/hold3_data2
add wave -noupdate -group into_design -format Literal /test/direct_test/in_stage2/hold4_data1
add wave -noupdate -group into_design -format Literal /test/direct_test/in_stage2/hold4_data2
add wave -noupdate -group into_design -format Literal /test/direct_test/in_stage2/prio_alu_in_cmd
add wave -noupdate -group into_design -format Literal /test/direct_test/in_stage2/prio_alu_in_req_id
add wave -noupdate -group into_design -format Literal /test/direct_test/mux_out1/req_data
add wave -noupdate -group into_design -format Literal /test/direct_test/mux_out1/req_resp
add wave -noupdate -group into_design -format Literal /test/direct_test/mux_out1/req_data1
add wave -noupdate -group into_design -format Literal /test/direct_test/mux_out1/req_data2
add wave -noupdate -group into_design -format Literal /test/direct_test/mux_out1/req_resp1
add wave -noupdate -group into_design -format Literal /test/direct_test/mux_out1/req_resp2
add wave -noupdate -group into_design -format Literal /test/direct_test/mux_out2/req_data
add wave -noupdate -group into_design -format Literal /test/direct_test/mux_out2/req_resp
add wave -noupdate -group into_design -format Literal /test/direct_test/mux_out2/req_data1
add wave -noupdate -group into_design -format Literal /test/direct_test/mux_out2/req_data2
add wave -noupdate -group into_design -format Literal /test/direct_test/mux_out2/req_resp1
add wave -noupdate -group into_design -format Literal /test/direct_test/mux_out2/req_resp2
add wave -noupdate -group into_design -format Literal /test/direct_test/mux_out3/req_data
add wave -noupdate -group into_design -format Literal /test/direct_test/mux_out3/req_resp
add wave -noupdate -group into_design -format Literal /test/direct_test/mux_out3/req_data1
add wave -noupdate -group into_design -format Literal /test/direct_test/mux_out3/req_data2
add wave -noupdate -group into_design -format Literal /test/direct_test/mux_out3/req_resp1
add wave -noupdate -group into_design -format Literal /test/direct_test/mux_out3/req_resp2
add wave -noupdate -group into_design -format Literal /test/direct_test/mux_out4/req_data
add wave -noupdate -group into_design -format Literal /test/direct_test/mux_out4/req_resp
add wave -noupdate -group into_design -format Literal /test/direct_test/mux_out4/req_data1
add wave -noupdate -group into_design -format Literal /test/direct_test/mux_out4/req_data2
add wave -noupdate -group into_design -format Literal /test/direct_test/mux_out4/req_resp1
add wave -noupdate -group into_design -format Literal /test/direct_test/mux_out4/req_resp2
add wave -noupdate -group into_design -format Literal /test/direct_test/out_stage1/out_data1
add wave -noupdate -group into_design -format Literal /test/direct_test/out_stage1/out_data2
add wave -noupdate -group into_design -format Literal /test/direct_test/out_stage1/out_data3
add wave -noupdate -group into_design -format Literal /test/direct_test/out_stage1/out_data4
add wave -noupdate -group into_design -format Literal /test/direct_test/out_stage1/out_resp1
add wave -noupdate -group into_design -format Literal /test/direct_test/out_stage1/out_resp2
add wave -noupdate -group into_design -format Literal /test/direct_test/out_stage1/out_resp3
add wave -noupdate -group into_design -format Literal /test/direct_test/out_stage1/out_resp4
add wave -noupdate -group into_design -format Logic /test/direct_test/out_stage1/scan_out
add wave -noupdate -group into_design -format Literal /test/direct_test/out_stage1/alu_result
add wave -noupdate -group into_design -format Literal /test/direct_test/out_stage1/prio_alu_out_req_id
add wave -noupdate -group into_design -format Literal /test/direct_test/out_stage1/reset
add wave -noupdate -group into_design -format Logic /test/direct_test/out_stage1/a_clk
add wave -noupdate -group into_design -format Logic /test/direct_test/out_stage1/b_clk
add wave -noupdate -group into_design -format Logic /test/direct_test/out_stage1/c_clk
add wave -noupdate -group into_design -format Logic /test/direct_test/out_stage1/alu_overflow
add wave -noupdate -group into_design -format Logic /test/direct_test/out_stage1/local_error_found
add wave -noupdate -group into_design -format Logic /test/direct_test/out_stage1/prio_alu_out_vld
add wave -noupdate -group into_design -format Logic /test/direct_test/out_stage1/scan_in
add wave -noupdate -group into_design -format Literal /test/direct_test/out_stage1/hold_data
add wave -noupdate -group into_design -format Literal /test/direct_test/out_stage1/hold_resp
add wave -noupdate -group into_design -format Literal /test/direct_test/out_stage1/hold_id
add wave -noupdate -group into_design -format Literal /test/direct_test/out_stage2/out_data1
add wave -noupdate -group into_design -format Literal /test/direct_test/out_stage2/out_data2
add wave -noupdate -group into_design -format Literal /test/direct_test/out_stage2/out_data3
add wave -noupdate -group into_design -format Literal /test/direct_test/out_stage2/out_data4
add wave -noupdate -group into_design -format Literal /test/direct_test/out_stage2/out_resp1
add wave -noupdate -group into_design -format Literal /test/direct_test/out_stage2/out_resp2
add wave -noupdate -group into_design -format Literal /test/direct_test/out_stage2/out_resp3
add wave -noupdate -group into_design -format Literal /test/direct_test/out_stage2/out_resp4
add wave -noupdate -group into_design -format Logic /test/direct_test/out_stage2/scan_out
add wave -noupdate -group into_design -format Literal /test/direct_test/out_stage2/alu_result
add wave -noupdate -group into_design -format Literal /test/direct_test/out_stage2/prio_alu_out_req_id
add wave -noupdate -group into_design -format Literal /test/direct_test/out_stage2/reset
add wave -noupdate -group into_design -format Logic /test/direct_test/out_stage2/a_clk
add wave -noupdate -group into_design -format Logic /test/direct_test/out_stage2/b_clk
add wave -noupdate -group into_design -format Logic /test/direct_test/out_stage2/c_clk
add wave -noupdate -group into_design -format Logic /test/direct_test/out_stage2/alu_overflow
add wave -noupdate -group into_design -format Logic /test/direct_test/out_stage2/local_error_found
add wave -noupdate -group into_design -format Logic /test/direct_test/out_stage2/prio_alu_out_vld
add wave -noupdate -group into_design -format Logic /test/direct_test/out_stage2/scan_in
add wave -noupdate -group into_design -format Literal /test/direct_test/out_stage2/hold_data
add wave -noupdate -group into_design -format Literal /test/direct_test/out_stage2/hold_resp
add wave -noupdate -group into_design -format Literal /test/direct_test/out_stage2/hold_id
add wave -noupdate -group into_design -format Literal /test/direct_test/priority_logic/prio_alu1_in_cmd
add wave -noupdate -group into_design -format Literal /test/direct_test/priority_logic/prio_alu2_in_cmd
add wave -noupdate -group into_design -format Literal /test/direct_test/priority_logic/prio_alu1_out_req_id
add wave -noupdate -group into_design -format Literal /test/direct_test/priority_logic/prio_alu1_in_req_id
add wave -noupdate -group into_design -format Literal /test/direct_test/priority_logic/prio_alu2_in_req_id
add wave -noupdate -group into_design -format Literal /test/direct_test/priority_logic/prio_alu2_out_req_id
add wave -noupdate -group into_design -format Logic /test/direct_test/priority_logic/prio_alu1_out_vld
add wave -noupdate -group into_design -format Logic /test/direct_test/priority_logic/prio_alu2_out_vld
add wave -noupdate -group into_design -format Logic /test/direct_test/priority_logic/scan_out
add wave -noupdate -group into_design -format Logic /test/direct_test/priority_logic/a_clk
add wave -noupdate -group into_design -format Logic /test/direct_test/priority_logic/b_clk
add wave -noupdate -group into_design -format Logic /test/direct_test/priority_logic/c_clk
add wave -noupdate -group into_design -format Logic /test/direct_test/priority_logic/local_error_found
add wave -noupdate -group into_design -format Logic /test/direct_test/priority_logic/scan_in
add wave -noupdate -group into_design -format Literal /test/direct_test/priority_logic/hold1_prio_req
add wave -noupdate -group into_design -format Literal /test/direct_test/priority_logic/hold2_prio_req
add wave -noupdate -group into_design -format Literal /test/direct_test/priority_logic/hold3_prio_req
add wave -noupdate -group into_design -format Literal /test/direct_test/priority_logic/hold4_prio_req
add wave -noupdate -group into_design -format Literal /test/direct_test/priority_logic/reset
add wave -noupdate -group into_design -format Literal /test/direct_test/priority_logic/cmd1
add wave -noupdate -group into_design -format Literal /test/direct_test/priority_logic/cmd2
add wave -noupdate -group into_design -format Literal /test/direct_test/priority_logic/cmd3
add wave -noupdate -group into_design -format Literal /test/direct_test/priority_logic/cmd4
add wave -noupdate -group into_design -format Logic /test/direct_test/priority_logic/delay1
add wave -noupdate -group into_design -format Logic /test/direct_test/priority_logic/delay2
add wave -noupdate -group into_design -format Logic /test/direct_test/priority_logic/cmd1_reset
add wave -noupdate -group into_design -format Logic /test/direct_test/priority_logic/cmd2_reset
add wave -noupdate -group into_design -format Logic /test/direct_test/priority_logic/cmd3_reset
add wave -noupdate -group into_design -format Logic /test/direct_test/priority_logic/cmd4_reset
add wave -noupdate -group into_design -format Literal /test/direct_test/priority_logic/prio_req1_id_q
add wave -noupdate -group into_design -format Literal /test/direct_test/priority_logic/prio_req2_id_q
add wave -noupdate -group into_design -format Logic /test/direct_test/priority_logic/prio_alu1_out_vld_q
add wave -noupdate -group into_design -format Logic /test/direct_test/priority_logic/prio_alu2_out_vld_q
add wave -noupdate -group into_design -format Logic /test/direct_test/shifter1/bin_ovfl
add wave -noupdate -group into_design -format Literal /test/direct_test/shifter1/shift_out
add wave -noupdate -group into_design -format Literal /test/direct_test/shifter1/shift_cmd
add wave -noupdate -group into_design -format Literal /test/direct_test/shifter1/shift_places
add wave -noupdate -group into_design -format Literal /test/direct_test/shifter1/shift_val
add wave -noupdate -group into_design -format Logic /test/direct_test/shifter1/local_error_found
add wave -noupdate -group into_design -format Literal /test/direct_test/shifter1/pos
add wave -noupdate -group into_design -format Literal /test/direct_test/shifter1/shiftleft
add wave -noupdate -group into_design -format Literal /test/direct_test/shifter1/shiftright
add wave -noupdate -group into_design -format Literal /test/direct_test/shifter1/tempshiftl
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {56 ps} 0}
configure wave -namecolwidth 201
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ps
update
WaveRestoreZoom {0 ps} {372 ps}
